### ISSUE TITLE
[Homework 4] Abstract Domains in Documentation

### ISSUE THREAD

**Issue by dnjsdnwja** [KAIST-IS593/is593-2020-spring#10]
![1](https://user-images.githubusercontent.com/61692251/81298514-d5de1780-90af-11ea-85ef-00ff30df125f.png)

I'm confused with the abstract domains given in the documentation.

According to the skeleton code, it seems
1. M# = A -> V#
2. V# = Z# x A# x F#
3. A# = powerset({null} U X U P U H)

Am I missing something?

**Comment by KihongHeo** [comment]
No. You are correct. That was my fault. 
And `M# = ({null} U X U P U H#) -> V#` (See H#)

**Comment by tomtomjhj** [comment]
* `𝔸 = {null} ∪ (𝕏 × 𝕀) ∪ ℙ ∪  ℍ`, `𝔸♯ = P(Location.t)`
* `Location.t = {null} ∪  𝕏 ∪ AllocaSite ∪ MallocSite`
    * `𝕀♯ = {·}`
    * `ℙ = AllocaSite × 𝕀`, `ℙ♯ = P(AllocaSite)`
    * `ℍ♯ = P(MallocSite)`
* `𝕄♯ = Location.t → 𝕍♯`
