### ISSUE TITLE
[Homework 4] cmp function in VALUE module type

### ISSUE THREAD

**Issue by dnjsdnwja** [KAIST-IS593/is593-2020-spring#11]
It seems having a cmp function (val cmp : Llvm.Icmp.t -> t -> t -> Numerical.t) in VALUE module type would be useful. Could we edit the module type VALUE for this?

**Comment by KihongHeo** [comment]
(I changed the answer since I misunderstood your question)

The value domain does include the numerical domain as a subpart. So you don't need to change the type.

**Comment by dnjsdnwja** [comment]
> Yes. See #6

The thing is that, VALUE module type in the skeleton code doesn't have cmp function at all.

**Comment by dnjsdnwja** [comment]
> (I changed the answer since I misunderstood your question)
> 
> The value domain does include the numerical domain as a subpart. So you don't need to change the type.

Since, in addition to numerical domain, power set domains (i.e. locations and functions) also have cmp function, I thought it would be beneficial to have cmp function in Value as well.

**Comment by KihongHeo** [comment]
Now I see what you mean.
I was thinking that the skeleton code already has it.
Yes. Please do so.
