### ISSUE TITLE
[Homework 4] How to define abstract semantics for powerset?

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#13]
Hi. I'm a little confused with the semantic functions for powerset.
According to the lecture notes, all semantic functions are defined as kind-wise liftings.
However, as far as I understood, pointwise lifting defines a Galois connection for a function to domains connected with Galois connection.
So I'm still confused to how the semantic functions for an element, say **cmp** for **Location**, extends to the semantic function for the powerset, in this case **cmp** for **P(Location)**. Can this also be explained by pointwise lifting? Because if so, I cannot see how. 
Thanks.

**Comment by KihongHeo** [comment]
"pointwise-lifting" is not only used for Galois connections but is a general tool to define something using its sub-components. 

You can recall how you did define `cmp` or some other operators for **intervals** from those for **integers**. So for LocSet or FunSet, you should define the best abstraction.

**Comment by KunJeong** [comment]
Oh, right. Thank you for the clarification.
