### ISSUE TITLE
[Homework 4] initial value of Allocsite

### ISSUE THREAD

**Issue by h2oche** [KAIST-IS593/is593-2020-spring#14]
Hi. I have a question.

What should be initial value of Allocsite? 
For example, what is the value of *a in following code?

```c
#include "homework.h"

int main() {
  int* a = malloc(); // a -> l, l -> ?
  int k = 10 / *a; // error?
  return 0;
}
```

I guess (Bot, {}, {}) (Top, {}, {}), and ([0,0], {}, {}) are reasonable choices for initial value, but I'm not sure of it.

**Comment by KihongHeo** [comment]
Please use bot.

**Comment by h2oche** [comment]
Okay, thanks!
