### ISSUE TITLE
[Homework 4] Section 4 in Homework document

### ISSUE THREAD

**Issue by TonyWild** [KAIST-IS593/is593-2020-spring#15]
In Section 4 of Homework.pdf, it says that abstract value is a pair of abstract integer, abstract stack memory address, and abstract heap memory address (Z#, P#, and H# respectively).

However, I believe the abstract value is a pair of abstract integer, abstract address, and abstract function. So instead of Z#, P#, and H#, should it be Z#, A#, and F#?

Thanks.

**Comment by KihongHeo** [comment]
Yes. You are right. That is a typo.
