### ISSUE TITLE
[Homework 4] Narrowing operator for values

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#17]
Hi again.
Currently, the PowSet functor returns a failure with the narrowing operator.
In the case of Sign domain that doesn't support narrowing, we can just widen and terminate and not narrow at all, but for Interval domain that is not possible.
Since a value contains Numerical, LocSet and FunSet, how can I define a proper narrowing operator for Values?
Thank you.

**Comment by KihongHeo** [comment]
As we define `widen` for Sign as `join`, you can define `narrow` for the power-set domains as `meet` (i.e., set intersection).

**Comment by KunJeong** [comment]
Aha. Then I guess it would be better to replace the `fail with "Unsupported"` with meet instead?

**Comment by KihongHeo** [comment]
Yes.
But in the homework, two arguments of the `narrow` will have always the same value because no widening for power-set is applied.

**Comment by KunJeong** [comment]
Hmm. I still don't see why this is the case. Isn't the two arguments of `narrow` generally the input and output of the abstract semantic function? How are these the same?

**Comment by KihongHeo** [comment]
(answer changed) You are right. Ignore the comment. Just `meet` for `narrow` is enough.

**Comment by KunJeong** [comment]
Oh I saw the change just now. Thank you.
