### ISSUE TITLE
[Homework 3] if_for_if.interval testcase

### ISSUE THREAD

**Issue by dnjsdnwja** [KAIST-IS593/is593-2020-spring#18]
In the given expected result of the if_for_if.interval analysis, it has got
Potential Division-by-zero @ advanced/if_for_if.c:main:23:31, %call = [0, +oo]
as one of the outputs.

However, my understanding is that since the outer for loop does comparison (i < x), x must be greater than zero (as i has initial value of zero) and so the division-by-zero cannot occur.

I believe this issue is related to one of the questions asked by "Jaehwang Jung" http://klms.kaist.ac.kr/mod/ubboard/article.php?id=347956&bwid=174013
. In other words, I think it is related the issue of filtering both sides when comparisons consist of variable at both sides.

![1](https://user-images.githubusercontent.com/61692251/81524916-edf2b700-938d-11ea-86ba-35804c487c52.PNG)

**Comment by goguma-chsong** [comment]
Sorry. That was my fault. I totally understand your opinion, and I will re-upload with newly updated score soon.
Thank you very much :)

**Comment by KunJeong** [comment]
Hi. It seems like the score has been updated, but the test cases have not. Could you please upload the new tests?

**Comment by goguma-chsong** [comment]
Sorry... ㅠㅠ I'll push them ASAP....
