### ISSUE TITLE
[General Llvm Question] Confusion between label and instruction

### ISSUE THREAD

**Issue by TonyWild** [KAIST-IS593/is593-2020-spring#19]
While doing homeworks, I'm still quite confused about difference between label and instruction. It seems like both uses "At_end", or "Before something" for finding the positions.
Are they actually a same thing in OCaml implementation, or is there a subtle difference between them?

Thanks.

**Comment by KihongHeo** [comment]
As in the lecture slides, each label is associated with an instruction. In the homework, an instruction is a`llvalue` type value, and a label is a `llpos` type value. Suppose `i` is an instruction, `Before i` is the label of the instruction.

**Comment by TonyWild** [comment]
Ah I see, I thought "At_end" and "Before i" is also applied to instructions. Thanks!
