### ISSUE TITLE
[Homework 4] correct and precise `filter` function in `Semantics`

### ISSUE THREAD

**Issue by ironore15** [KAIST-IS593/is593-2020-spring#21]
In my opinion, filter function should applied recursively.

For example,
```
%a = alloca i32
%b = load i32, i32* %a
%cmp = icmp eq i32 %b, 0
br i1 %cmp, label %label1, label %label2
```
then should filter the Location (Variable %b), but also filter the Location (Alloca %a).

Implementing this feature will make analyzer more precise, but I don't know how to achieve it.
Is this possible with only current and next label?

**Comment by KihongHeo** [comment]
That is a very good point. If I understand you correctly, (conceptually)
```c
b = TOP;
a = b;
if (a < 10) {
   // here, you want to filter b as well as a, right?
}
```

In general, this kind of reasoning requires more advanced analysis techniques called **relational analysis** that keeps track of relationships between variables (e.g., `a = b`, `c - d <= 1`, etc). But our current abstraction (memory with interval or sign) is non-relational so unable to generally handle the problem.

But we can handle some common and simple cases like the particular case you mentioned (I guess it is very common in LLVM IR). You can traverse the corresponding instructions for variables `b` and `a` from the branch instruction. Remember that, in LLVM, a variable also represents the instruction where it is defined. So we don't need additional labels I think.

**Comment by ironore15** [comment]
It helps a lot. Thanks!!
