### ISSUE TITLE
[Homework 4] Different definition of abstract Value domain

### ISSUE THREAD

**Issue by ironore15** [KAIST-IS593/is593-2020-spring#22]
Currently, V# is defined in Z# * A# * H#.

But LLVM IR is strongly typed, and all type conversion has explicit instructions.

Since we didn't implement type conversion instructions such as `inttoptr`,
we can assume that there is no type conversion in given IR, and it means that all variables can't be two or more values of Numerical, Location, Function simultaneously.

If the assumption is true, why do we use Z# * A# * H#, instead of Z# ∪ A# ∪ H#?

**Comment by KihongHeo** [comment]
Yes. You are right. The design is just for generality, and does not have any special meaning in our setting.

**Comment by ironore15** [comment]
Thanks for quick feedback!
