### ISSUE TITLE
[Homework 4] function and parameters of call

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#23]
Hello.
I tried to use `Llvm.operand` to get the function and the parameters of a `call` instruction, but the operand order doesn't seem to be as I anticipated. (for example 5, operand 0 was the parameter and operand 1 was the function. I'm not sure for cases with more parameters.)
Is there a better way to get the function and the parameters in a call instruction?

**Comment by tomtomjhj** [comment]
https://llvm.org/doxygen/classllvm_1_1CallBase.html#a598efe23bbf3bd82fa6b6a5588aa58b9
The last operand is the function being called. 
e.g. See `Utils.is_input`.

**Comment by KunJeong** [comment]
Oh great! I thought I might be using the wrong function. Thanks!
