### ISSUE TITLE
[Homework 4] a few more questions about function call

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#24]
Hi. Sorry for the repetitive questions, but I'm facing many problems with function call.

I have two questions.
1. Should we check the arity of functions and the calls? That is, how should we treat the case where f(int x) is called with two parameters?
2. How can we get the label for the parameter of f? By using `Llvm.operand`, I only get the constant values that are passed as an argument. However, I want to get the x in f(x), and assign a value to this x. I thought `Llvm.param` could do that, but I'm getting segmentation faults even when the index seems to be within range.

Thank you.

**Comment by KihongHeo** [comment]
Hi. No problem. Your questions will help other students.

1. Assume that input programs are all valid and well-typed. And also assume there is no variadic parameter (like  `int f(int x, ...)` in C). So ignore such a case. But you have to handle correctly defined and called functions with multiple parameters.

2. I guess you are using `Llvm.param` with function call instructions, which is invalid. `Llvm.param` is an API for function **definition**, not function call. So at the call site, you have to get the function definition (i.e., function value). See the semantic definition in the document (f \in eval#(E0, m) ...). Can you try `Llvm.param` on function defs?

**Comment by KunJeong** [comment]
By function definition, do you mean the elements of `FunSet`? If so, I believe I'm already doing so, although I'm not exactly sure what part of my `call` code creates the problem.

**Comment by KihongHeo** [comment]
Yes. Then it seems strange. 
Maybe an array out-of-bound error when you access a parameter?
I think you can restructure your code with `Llvm.fold_left_params` or `Llvm.params` and narrow down the problem.

**Comment by KunJeong** [comment]
Oh, that's a great idea. Thank you.

**Comment by KunJeong** [comment]
It seems like there is no particular `Location` for the parameter. The fault occurs on `Utils.get_function param`, where `param` is obtained from `Llvm.param function`.
For example, in example5, 
`define void @f(i32 %x) #0 !dbg !8`
is the place where x is defined. So printing the instruction of param using `Utils.string_of_instr` gives `i32 %x`, which is correct. However, it seems like this param is different from ordinary instructions, as its `Label` is vague and `Utils.get_function` does not work. 

Update: I've fixed the issue (for now) by using `Llvm.param_parent` instead. Please ignore the comment.

**Comment by KihongHeo** [comment]
I don't fully understand how you fixed. But function parameters should be treated as local variables, not as allocsites or alloca-site (if so, how do you differentiate multiple parameters?). In the skeleton code for `eval`, you can see how `Llvm.ValueKind.Argument` is used.

**Comment by KunJeong** [comment]
Yes you are right. The fix was of a minor detail, and the problem was actually from something else. I'll create a new issue.

**Comment by KunJeong** [comment]
Hi. I have a followup question about question 1.
Based on example5, there could be the case where f has two parameters and g has one parameter, but fp could have both in certain cases considering the context-insensitivity. In this case, the original program might be correctly typed but the analysis might have different number of arguments and parameters. Do I need to treat such a case?

**Comment by KihongHeo** [comment]
I don't understand. Why does f have two parameters? We cannot call `f` with >=2 parameters in a normal way, no?

**Comment by KunJeong** [comment]
I guess my explanation was misleading. I was trying to describe something like the following:
```c
void f(int x, int y){...}
void g(int x){...}
int main(){
    void (*fp)(int);
    int n = input();
    if (n<0) fp = f;
    else fp = g;
    (*fp)(-1);
}
```
where fp could be both a function with one parameter and a function with two parameters.

**Comment by KihongHeo** [comment]
I see. But does that program pass the C type checker? The type of fp describes that the function takes only one argument.

Anyway, please assume that there is no such case. All the functions that are bound to a function pointer will have the same type (i.e., void return and the same number of parameters in this homework).

**Comment by KunJeong** [comment]
Oh, I forgot that `void (*fp)(int)` also defines the parameter types. So I guess it doesn't matter since it's invalid in C as well. Thank you.
