### ISSUE TITLE
[Homework 4] new question about worklist algorithm

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#25]
Hi.
In the narrowing phase of the worklist algorithm, what happens if there are no previous labels that can reach the current working label **w**, like for the first instruction of the main function?
<img width="339" alt="Screen Shot 2020-05-13 at 8 36 30 AM" src="https://user-images.githubusercontent.com/10477004/81755836-da159500-94f4-11ea-8994-b21addd81c9c.png">

As far as I can guess, since there are no **l** that transition to **w**, at line 10 it assigns the empty set (bottom) to **m_new**, and since the if condition is satisfied, it applies narrowing. However, since our narrowing is **meet**, this results in the new **m_new** going to bottom as well.

This is exactly what my code is doing at the moment. I made a temporary fix by returning **m_old** when **m_new**is bottom, but I'm not sure if this is correct. Can you help me?

Thank you.

**Comment by KihongHeo** [comment]
Your understanding is correct.
And your temporary fix is also a correct narrowing operator that satisfies the safety condition. 
I guess you are missing the **initial memory**. In our homework, the first instruction of the main function does have an abstract memory. See the `initialize` function and the last paragraph of Section 2 in README.

I hope this helps. But if you still have the same problem, leave more questions below.

**Comment by KunJeong** [comment]
Yes, but the initial abstract memory is **m_old** during the iteration. Isn't **m_new** still empty, since the first instruction is unreachable?

I guess my temporary fix is working for now. But I still seem to have an error somewhere in the worklist algorithm, so I'm not entirely sure. I'll let you know.
