### ISSUE TITLE
[OCaml Question] Syntax error in D.CallGraph.CallSites.empty

### ISSUE THREAD

**Issue by TonyWild** [KAIST-IS593/is593-2020-spring#26]
This might be a silly question, but `D.CallGraph.CallSites.empty` in semantics.ml causes a syntax error in `empty`. It says "Error: Syntax error: operator expected".
What is wrong with that part?

**Comment by KihongHeo** [comment]
I don't see any problem with `D.CallGraph.CallSites.empty` itself.
Maybe there is another syntax error near that part?

**Comment by TonyWild** [comment]
I cannot find the error until now :(
I tried replacing `D.CallGraph.CallSites.empty` to `D.callgraph.callsites.empty` and `callgraph.callsites.empty`, but none of them work. (3 lines from above in the picture)
All had the same syntax error issue.

![image](https://user-images.githubusercontent.com/18462177/81783195-f554c480-9535-11ea-94a1-6954d5593ef5.png)

**Comment by KihongHeo** [comment]
I see. You cannot use `D.CallGraph.CallSites.empty` in pattern matching. That is not a "pattern". Just a name of a value. 
You should try something like
```ocaml
if D.CallGraph.callsites_of f callgraph |> D.CallGraph.CallSites.is_empty then
  (* your code *)
else
  (* other code*)
```

**Comment by TonyWild** [comment]
Ah, I see. The pattern matching itself was a problem. Now it properly works, thanks!
