### ISSUE TITLE
[Project] Typo in slides

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#28]
Hi.
Currently, the slides for the project say that the presentation is 6/17, 6/22, 6/24 at one point and 6/15, 6/17, 6/22 at another. Which one is correct?
Thank you.

**Comment by KihongHeo** [comment]
Oh, Yes. Thanks. 6/17, 6/22, 6/24 are correct.

**Comment by KunJeong** [comment]
Thank you. Should I keep this issue open?

**Comment by KihongHeo** [comment]
I put it in the schedule table. Let me close.
