### ISSUE TITLE
[Project] proposal guidelines

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#29]
Hi. Are there any recommended quidelines regarding the proposal? i.e) what should be in it, how detailed it should be, etc. Also, is it sufficient to submit a 1-page pdf? Thank you.

**Comment by KihongHeo** [comment]
Basically the same as described in the [slides](https://github.com/KAIST-IS593/is593-2020-spring/blob/master/slides/project.pdf).

- Motivation: What problem do you want to solve and why is it important? For example, specific target properties, limitations of static analysis we learned in the lecture, etc.

- Approach: How do you solve the problem? For example, high-level designs of your abstract domains, abstract semantics, implementation, etc.

- Expected result: How do evaluate your approach? For example, running the analyzer on a suite of handcrafted example programs, realworld Linux utilities, and so on.

- Page limit: It up to you. But no more than 2 pages. If you describe a more concrete idea, I can give you more detailed feedback.

**Comment by KunJeong** [comment]
Thank you for the detailed explanation!
