### ISSUE TITLE
[Homework 3] Naive fixed point algorithm worklist

### ISSUE THREAD

**Issue by TonyWild** [KAIST-IS593/is593-2020-spring#3]
Hi, I'm Sungu Lee. I'm now trying working analysis by Naive fixed point algorithm, which seems a worklist algorithm but everytime worklist does not change.
So I tried with D.Worklist.fold trying to gather all of memories in the next step. I wanted to execute program with order (from start to end with respect to the input program) but D.Worklist.fold does not loop Worklist in program order.
So I was wondering if I have to gather "previous labels" even with Naive algorithm, or is there a good way to make sure D.Worklist.fold does loop in correct order.
Thanks!

**Comment by TonyWild** [comment]
That was a different problem I think. It seems to work as correct order!

**Comment by KihongHeo** [comment]
It is nice for you to find a problem. 

A comment: program analysis does not have to be performed in program execution order. Even totally revered order of exploration guarantees the correctness.
