### ISSUE TITLE
[Project & Lecture10] Abstract domains for relational analysis

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#31]
Hi. I'm currently experiencing some difficulties in defining the abstract domain for my project.
My topic incorporates a type of (directed) relational analysis, and I want to ask how to define abstract domains for such analyses.

I think the octagon domain in Lecture 10 could be a good example to help grasp the intuition. How would one define the abstract domain of the octagon domain? It seems like there's a value for (x,y) instead of a value for x as usual, so I don't understand how the set of integers is mapped into this 2-dimensional domain.

**Comment by KihongHeo** [comment]
It sounds really good that you want to design and implement a relational domain.

The octagon domain abstracts a set of **memories** as a set of linear constraints in a certain form as described in the lecture slide: `(+-x) - (+-y) <= c` . Suppose two concrete memories with two variables are as follows: `{x = 1, y = 2}`, and `{x = 10, y = 11}`. The abstraction with octagon domain will be the following set of linear constraints on `x` and `y`:
- x <= 10 (i.e., x's coefficient is 1 and y's coefficient is 0)
- -x <= -1  (i.e., x >= 1)
- x - y <= -1
- y - x <= 1
- ...

In the implementation, the above set of constraints can be succinctly encoded as a 2-d table. Each cell in the 2-d table of the octagon domain represents the upper bound of the diff of the two variables. Suppose `M` is the 2-d table. Then `M[x][y] = 1` is an encoding of constraint `y - x <= 1`.

Such 2-d table is called "difference bound matrix".
https://en.wikipedia.org/wiki/Difference_bound_matrix
https://kihongheo.kaist.ac.kr/papers/spe17.pdf  (see 4.1 and 4.2)

What do you mean by "directed" relational analysis? Depending on your purpose, you can make a simpler relational domain.

**Comment by KunJeong** [comment]
Okay, that makes sense. I guess I was stuck on the thought that there should be a **numerical** domain, and the thought that there should be some correspondence between the concrete domain and the abstract domain.
By directed, I meant the case where x has some relationship with y but y does not have a relation with x (like class inheritance relation, for instance). I thought that the octagon domain would be somewhat symmetric, but since it's implemented as such, I guess it's already directed in a sense.
I think now I get how to construct my domain. Also, your paper is really helpful..thank you!
One minor question: how does the DBM store `x <= 10`? At a glance, it seems like M[x][x] = 10 is not how it's done.

**Comment by KihongHeo** [comment]
If I understand correctly, the octagon domain is "symmetric" in that sense. It can represents all of the following contraints:
- x - y <= c
- (-x) - y <= c
- x - (-y) <= c 
- (-x) - (-y) <= c

Each of them represents 4 diagonals in an octagon geometrically.

`x <= 10` is represented as`x - (-x) <= 20` in the octagon domain.

If you don't need all the combinations of octagon constraints and only need one-side of contraints, maybe something like the pentagon domain would be reasonable. See figure 2 in (https://dl.acm.org/doi/abs/10.1145/1363686.1363736).

**Comment by KunJeong** [comment]
Thank you! The reference materials you gave helped a lot
