### ISSUE TITLE
[Homework 5] Dependency in shell scripts and a minor issue in README

### ISSUE THREAD

**Issue by hyunsukimsokcho** [KAIST-IS593/is593-2020-spring#32]
I see problematic dependency in given shell scripts. (`test/example*.sh`) These scripts assume that target `example*.ll` file is located at the command execution path.

My suggestion is adding `cd "{0%/*}"` at the beginning of each shell scripts. For example, `example1.sh` will become:
```sh
#!/bin/bash
cd "${0%/*}"

NAME=example1

clang -o ${NAME} ${NAME}.ll >&/dev/null && ./${NAME}

```

Then, the output (without implementation of `ddmin`) becomes:
```
Iteration 1, # Instrs = 10
-- running dd_global
Fatal error: exception Failure("Not implemented")
```

My idea is fixing shell scripts in a way that is agnostic to the path being executed (by forcing `cd` to desired working directory). [ref](https://stackoverflow.com/questions/3349105/how-to-set-current-working-directory-to-the-directory-of-the-script)

---

Also, in README, I think `Function` is rather `Global` according to the code (`src/debloat.ml`):

**Comment by KihongHeo** [comment]
Thanks for the good suggestion. It will be good to use such thing if you want to more generalize the tool.

TA will run your code under the same directory with each shell script. So do not worry about the evaluation.

**Comment by KihongHeo** [comment]
I fixed README yesterday. So students who checkout after my fix will have the correct document.

**Comment by hyunsukimsokcho** [comment]
Thanks for the confirm and prompt reply!

**Comment by KihongHeo** [comment]
Reopen for other students.

**Comment by KunJeong** [comment]
Hi. I don't think I fully understand what's going on here. Since I checked out earlier than your update, may I ask for the correct fix?

**Comment by KihongHeo** [comment]
Nothing serious but just a typo in README.

`Function` -> `Global`

**Comment by KunJeong** [comment]
Hmm. The error in #33 still occurs even when I run `../debloater example1.sh example1.ll` in the test directory. Perhaps it's a different issue?

**Comment by KihongHeo** [comment]
Perhaps,

```
../debloater ./example1.sh example1.ll
```
?

**Comment by KunJeong** [comment]
Oh, that works well. Thank you.

**Comment by KihongHeo** [comment]
Good. Sorry I am not a human-friendly front-end programmer.

**Comment by KunJeong** [comment]
Haha no it's fine. I've never understood why the `./` is necessary though.
