### ISSUE TITLE
[HW5] The test script initially failed

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#33]
Hi. I'm currently getting the error "The test script initially failed" when running `./debloater test/example1.sh test/example1.ll`. However, as I understand, this error comes before my code for ddmin is run, so my code is not the cause. This same error happens for all 3 test cases.
What am I doing wrong? I ran make in both the root and the test directory.

**Comment by KihongHeo** [comment]
Hi,

Maybe it is related to #32?

**Comment by KunJeong** [comment]
Oh, I see. Closing for now.
