### ISSUE TITLE
[Opam] opam commands not working in VM

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#35]
Hi. It's my first time using the provided VM via kvpn. I'm encountering some issues with opam while trying to install ocamlformat and merlin.
`opam install [something]` and `opam update` `opam upgrade` all fail with the following output.
```
opam: "open" failed on /home/student/.opam/is593-4.08.0/.opam-switch/lock: Permission denied
Backtrace:
  Raised by primitive operation at file "src/core/opamSystem.ml", line 845, characters 13-73
  Called from file "src/core/opamFilename.ml" (inlined), line 372, characters 33-82
  Called from file "src/state/opamSwitchState.ml", line 99, characters 4-70
  Called from file "src/state/opamSwitchState.ml", line 797, characters 11-33
  Called from file "src/state/opamRepositoryState.ml", line 265, characters 14-18
  Re-raised at file "src/core/opamStd.ml", line 1164, characters 4-38
  Called from file "src/state/opamGlobalState.ml", line 162, characters 14-18
  Re-raised at file "src/core/opamStd.ml", line 1164, characters 4-38
  Called from file "src_ext/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line 27, characters 27-34
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line 106, characters 32-39
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line 136, characters 18-36
  Called from file "src_ext/cmdliner/src/cmdliner.ml", line 251, characters 22-48
  Called from file "src/client/opamMain.ml", line 209, characters 8-15
  Called from file "src/client/opamMain.ml", line 136, characters 6-10
```
`opam list` works fine, and I can check that everything else is pre-installed correctly.
How can I fix this issue? Thank you.

**Comment by hyunsooda** [comment]
Did you try to install with command `sudo`?

I faced that issue when I install without `sudo` command and now it is installed with `sudo` command

Please try this command again
- `sudo opam install ocamlformat`

For Your Information,
I have constructed all the environments using the root account, not the student, so this issue is happened, sorry. Please type your command with `sudo` at all times whenever you do something via opam

**Comment by KunJeong** [comment]
Thank you, it works.
