### ISSUE TITLE
[Project] Delayed Submission

### ISSUE THREAD

**Issue by KihongHeo** [KAIST-IS593/is593-2020-spring#38]
A student asked me if a delayed submission is acceptable.

Yes. Delayed submissions are acceptable and the penalty is the same as usual.

**Comment by hyunsikjeong** [comment]
@KihongHeo 
As previous announcements (https://github.com/KAIST-IS593/is593-2020-spring/issues/37), it is okay to upload slides after the presentation.
But isn't it checked as a late submission in Github Classroom? I'm just curious whether there's a way to check it properly or not...

**Comment by KihongHeo** [comment]
No problem. TA will check using his own script.
