### ISSUE TITLE
[Project] Presenters

### ISSUE THREAD

**Issue by KihongHeo** [KAIST-IS593/is593-2020-spring#39]
Hi,

We will have 5 (17th), 5 (22nd), and 6 (24th) presenters for each day.

I randomly picked up 5 presenters for Wednesday this week:

17th: 안승민, 이선구, 김은진, 최원우, 홍재민

Please leave an ack as a comment here once you read this announcement.

Thanks.

**Comment by dnjsdnwja** [comment]
Got it

CHOI WONWOO

**Comment by h2oche** [comment]
I checked!

**Comment by Medowhill** [comment]
I see.

**Comment by TonyWild** [comment]
Checking for 이선구!
