### ISSUE TITLE
[Homework 4] Abstract semantics of a null dereference

### ISSUE THREAD

**Issue by Medowhill** [KAIST-IS593/is593-2020-spring#4]
Hi.

In homework 4, what is the abstract semantics of a null dereference? If the concretization of `eval_E(m)` contains a null pointer, then does `x := load E` make the abstract value of `x` become `Top`, like division by zero in the previous homework? In addition, what does happen when there is a store operation to a null pointer? If the concretization of `eval_E1(m)` contains a null pointer, then does `store E0 E1` make the abstract values of all the variables become `Top`?

Thank you.

**Comment by KihongHeo** [comment]
Hi.
Let us define the abstract semantics as the best abstraction for the case. And for all **concrete** memory M, `M(null) = bot`.

If we define the case as `Top`, the analysis result becomes horrible if `x` is a pointer. Right? Instruction `*x = 1` has to apply weak update for all abstract memory addresses.

**Comment by Medowhill** [comment]
Then, if a null pointer is the only possible value for `x`, then `*x = 1` leads to the bottom. Am I correct?

**Comment by KihongHeo** [comment]
Correct.

**Comment by Medowhill** [comment]
Thank you!
