### ISSUE TITLE
[Final] Announcement

### ISSUE THREAD

**Issue by KihongHeo** [KAIST-IS593/is593-2020-spring#40]
The final exam will happen on Jun 29 (9 - 10:30, including submission) over Zoom. It will be an open-book exam.

- Instructions:
  - Checkout the repository for final exam: https://classroom.github.com/a/za8czkx-. Sign the document (regarding honor code and personal information collection) and submit before the exam.
  - Turn on your camera during the exam. The Zoom sessions will be recorded for preventing cheating.
  - Example papers will be distributed via Zoom's screen share during the session.
  - Submit your answer sheet to the GitHub repository after the exam. (e.g., upload photos of your handwritten answer sheets) The detailed instructions are described in the repository.
  - no coding questions
  - I will show you the exam paper via Zoom's screen sharing

For someone who is in a different time zone at this moment, we will have a separated session on Jun 29 (14 - 15:30). The detailed instructions will be the same. 

If you have any further concerns and suggestions for fairness, feel free to contact me.

**Comment by KihongHeo** [comment]
More answers to additional questions from students:
- discussions with others are prohibited
- searching on the internet is prohibited

**Comment by hyunsooda** [comment]
Students can adjust the view ratio in the Zoom to fit the specific questions.

View Options --> Zoom Ratio --> 100, ... 300%
![Screenshot from 2020-06-24 11-54-36](https://user-images.githubusercontent.com/12508269/85493249-862cbe80-b611-11ea-868c-b6f2ad39d032.png)
