### ISSUE TITLE
[Homework 6] Segmentation fault in compilation of output .ll

### ISSUE THREAD

**Issue by hyunsukimsokcho** [KAIST-IS593/is593-2020-spring#45]
In example 1, I came up with a program which is printed as follows:
```
If ((X == Y), If ((Y <= X), X, 1), If ((X == Y), 1, ((Y - 0) + X)))
```
Although it seems to satisfy the spec of `example1.csv`, the output .ll file (`example1.topdown.ll`) causes **segmentation fault** in compilation with clang.

Is there any limitations in converting pseudo-program (`Language.t`) to LLVM IR?

**Comment by KihongHeo** [comment]
Thanks for the report.
I fixed the bug. You should replace src/language.ml with https://www.dropbox.com/s/vkimlikqdpjzud4/language.ml?dl=0.

**Comment by hyunsukimsokcho** [comment]
Thanks for the prompt and working patch!
