### ISSUE TITLE
[Random Program Generator] not working

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#46]
Hi. I can't seem to get the generator to work. After running make, the "generator" executable is generated. However, running `./generator 5 5 > example.cs`v returns the error `zsh: no such file or directory: ./generator`. What am I doing wrong here?

I posted an issue on the generator repo, but realized other students probably weren't following the repository. Has anyone encountered the same problem?

**Comment by KihongHeo** [comment]
Are you sure that the generated executable is a valid one? Please check if it is a valid symbolic link.

**Comment by KunJeong** [comment]
I checked, and the `_build` directory isn't there in the first place.

**Comment by KunJeong** [comment]
I found the source of the error. I had cloned the generator inside the `test` directory for hw6 to make typing file paths easier, and I think that broke the make. Is there a fix for this?

**Comment by KihongHeo** [comment]
Can you just delete the cloned dir in test and clone the repository again outside of hw6?

**Comment by KunJeong** [comment]
Yes I will do so. I'm curious why it causes a bug though.

**Comment by hyunsooda** [comment]
That's a wrong symbolic link problem when you do `make`.

In your situation, you should resolve the symbolic link path like below.

[Makefile]
10: `$(LN) ../../_build/default/test/random-program-generator/src/main.exe $(EXE)`

**Comment by KunJeong** [comment]
Oh I see. Thank you!
