### ISSUE TITLE
[Homework 6] Travis CI failed

### ISSUE THREAD

**Issue by kyeongmincho** [KAIST-IS593/is593-2020-spring#47]
[Here](https://travis-ci.com/github/KAIST-IS593/is593-2020-spring-hw6-drzix/jobs/353137247) is the job. It fails when `opam init`

But I expect that maybe evaluation of my code will be OK because it works well on my local environment.

**Comment by hyunsooda** [comment]
Don't worry. TA(Changhoon Song) will ignore the output of Travis CI and he will test your work on his local environment.

**Comment by kyeongmincho** [comment]
Thanks!
