### ISSUE TITLE
[Homework 4] `of_allocsite` in the module `Location`

### ISSUE THREAD

**Issue by Medowhill** [KAIST-IS593/is593-2020-spring#7]
Hi.

Currently, `of_allociste` in the 84th line of `domain.ml` has one unused parameter, and it seems to need to be removed.
```ocaml
  let of_allocsite _ a = Allocsite (Label.make a)
```
->
```ocaml
  let of_allocsite a = Allocsite (Label.make a)
```

Thank you.

**Comment by KihongHeo** [comment]
Thanks a lot. You are acting like a TA. I really appreciate it.
