### ISSUE TITLE
Memory operation type

### ISSUE THREAD

**Issue by tomtomjhj** [KAIST-IS593/is593-2020-spring#8]
The type declarations of memory operation in `MEMORY_DOMAIN` seem to be wrong.
For example, the signature of weak update doesn't make sense because it accepts a single location.
```ocaml
val weak_update : Location.t -> Value.t -> t -> t
```
I think this and other functions should get `LocSet` or `Value.t` instead of `Location.t`.

Also the definition `𝕄♯ = 𝔸♯ → 𝕍♯` should be updated to the definition similar to the one in the lecture7 p10.

**Comment by KihongHeo** [comment]
Hi. 
Nice suggestion. But you can use the `weak_update` function for all possible locations. The effect will be the same. Please do so for this assignment.

For `𝕄♯ = 𝔸♯ → 𝕍♯`, you are right.
